version: '3'

services: 
  mysql:
    container_name: mysql
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
  ohmydash:
    image: stdatatech/ohmydash
    ports: 
      - 3000:3000
    environment: 
      PROFILE: mysql
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: pass1234
    command: sh -c 'dockerize -wait tcp://mysql:3306 -timeout 300s -wait-retry-interval 5s /opt/ohmydash/bin/start.sh'