version: '3'

services: 
  mysql:
    container_name: mysql
    image: qos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pa5s!@34
  ohmydash:
    image: stdatatech/ohmydash
    ports: 
      - 3000:3000
    environment: 
      LICENSE_SERVER_URL: http://ohmydash.stdatatech.com:8060/api/v1/clients
      PROFILE: mysql
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Pa5s!@34
   depends_on: 
     - mysql